### ISSUE TITLE
USER STORY - Proivde certian opinion to running topics or events

### ISSUE THREAD

**Issue by KimBergstroem** [KimBergstroem/love-running#1]
**In order to** provide my opinion with regards to a certian running topic or event, **as a** user, **I can** select and submit an answer from the poll.

## Acceptance Criteria:
- Acceptance Criteria 1: The option should be provided as a form.
- Acceptance Criteria 2: The checkbox should be "checked" by default.
- Acceptance Criteria 3: The option should appear next to the submit button for submitting.
- After submitting the defualt submission confirmation should be adjusted to include the user name.

## Tasks:
- [ ] Update the view: the pool design (HTML and CSS) to include the checkbox and to show the name of the submitter
- [ ] Create a new field in the model to track the username
- [ ] Update the controller function
- [ ] Update the unit test scripts
- [ ] Test the functionality
